Python does not have built-in supoort for arrays, but list can be used instead.

WHY ARRAY..??

for example we have 1000 of records [cars] stored in a single varibale and we want to find a specific one.

LIST --> it will iterate thorugh each of the value and gives the matched one.
ARRAY --> gives us the specific one using indexing 

In [7]:
%pip install numpy
import numpy as np


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [8]:
array1 = np.array([1, 2, 3, 4, 5])
print(array1)

[1 2 3 4 5]


In [9]:
print(array1 * 2)

[ 2  4  6  8 10]


In [10]:
multi_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(multi_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(multi_array * 2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [15]:
# Typecode during initialization to define C-type

import array as arr

arr1 = arr.array('i', [1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))

array('i', [1, 2, 3, 4, 5])
<class 'array.array'>


In [16]:
for i in range(0, len(arr1)):
    print(i, end = ',')
    print(arr1[i], end = '\n')

0,1
1,2
2,3
3,4
4,5


In [19]:
array2 = arr.array('i', [2,4,6,8,10,12,14,16,18,20])
print(array2)

array2.insert(0, 0)
print(array2)

array2.append(22)
print(array2)

array('i', [2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
array('i', [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
array('i', [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22])


In [21]:
print(array2[4])

8


In [22]:
array2.remove(22)
print(array2)

array('i', [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20])


In [24]:
array2.pop(0)
print(array2)

array('i', [2, 4, 6, 8, 10, 12, 14, 16, 18, 20])


In [25]:
array2[2] = 100
print(array2)

array('i', [2, 4, 100, 8, 10, 12, 14, 16, 18, 20])
